spring.application.name=HestIA
spring.datasource.url=jdbc:postgresql://localhost:5432/hestia
spring.datasource.username=postgres
spring.datasource.password=hestia15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
